import type { CtaButton } from "./home";

export type SolutionsPageData = {
  metaTitle: string;
  metaDescription: string;
  hero: {
    eyebrow: string;
    titleLines: string[];
    body: string;
  };
  personasSection: {
    eyebrow: string;
    title: string;
    body: string;
    personas: {
      role: string;
      iconKey: string;
      color: string;
      pain: string;
      value: string;
      benefits: string[];
    }[];
  };
  solutions: {
    id: string;
    badge: string;
    title: string;
    challenge: string;
    solution: string;
    capabilities: string[];
    outcomes: string[];
    iconKey: string;
    color: string;
  }[];
  finalCta: {
    title: string;
    body: string;
    cta: CtaButton;
  };
};

export const solutionsDefaults: SolutionsPageData = {
  metaTitle: "Solutions — Merlin Works in Every Building. Every Operation.",
  metaDescription: "Deployed at 5,000+ sites across France and Europe. From smart offices and building management to manufacturing, airports, healthcare, and nuclear power plants — Merlin brings Physical AI to the real world.",
  hero: {
    eyebrow: "SOLUTIONS",
    titleLines: ["Merlin Works in Every Building.", "Every Operation."],
    body: "Deployed at 5,000+ sites in France and across Europe — from smart offices and building management to industrial manufacturing, airports, healthcare, and nuclear power plants. Merlin and Adaptiv devices bring Physical AI to the real-world environments where it matters most.",
  },
  personasSection: {
    eyebrow: "Built for the People Who Run Real Operations",
    title: "Who Physical AI Is For",
    body: "Merlin is not a dashboard for analysts. It is an AI co-worker for the people responsible for buildings, factories, and operations — who need intelligence that acts, not just reports.",
    personas: [
      { role: "Building Owner", iconKey: "owner", color: "#FF00B2", pain: "30–40% of booked meeting rooms go unused. Energy runs on fixed schedules, not actual occupancy. Cleaning crews follow routes whether a space was used or not. You have no visibility into how your assets are actually performing — just cost lines going up.", value: "Merlin turns your buildings into self-optimising assets. Recovering just 20% of ghost-booked rooms in a 200-person office with 30 rooms is equivalent to adding 6 rooms — saving $150K–$250K in avoided lease expansion. Energy savings of 10–30% on lighting and HVAC. Cleaning labor costs cut 40–55% through demand-driven dispatch. Every gain is measurable and provable to tenants.", benefits: ["$150K–$250K saved in avoided lease expansion", "10–30% energy cost reduction", "40–55% cleaning labor savings", "Predictive maintenance — issues flagged before failure"] },
      { role: "Facility Manager", iconKey: "facility", color: "#14b8a6", pain: "Your day is a constant stream of reactive requests — stockout complaints from bathrooms, ghost-booked meeting rooms no one released, HVAC running full blast in empty floors. 30–40% of rooms sit vacant after booking. Cleaning follows fixed schedules, not actual demand.", value: "Merlin replaces fixed schedules with demand-driven operations. VOC levels, visit counts, feedback trends, and dispenser levels drive cleaning dispatch — cutting labor costs 40–55% while improving occupant satisfaction 15–20%. Ghost bookings are detected within minutes and rooms released automatically. CO₂-flat rooms with lights on are flagged as energy waste in real time.", benefits: ["Near-elimination of stockout complaints", "Ghost bookings detected and released in minutes", "Room-level energy waste detection", "Automated compliance and service proof"] },
      { role: "Factory Manager", iconKey: "factory", color: "#6366f1", pain: "Unplanned downtime destroys your throughput targets. You find out about equipment failures when lines stop, not before. Quality deviations are caught too late. Your operators react — they can't anticipate.", value: "Merlin monitors your machines continuously, not periodically. Vibration patterns, thermal signatures, and cycle anomalies are detected before failure. Smart Displays on the floor give operators real-time KPIs and Merlin-driven alerts — so your team acts before the line stops.", benefits: ["Fewer unplanned stoppages", "Condition-based maintenance", "Automated quality checks", "OEE visibility in real time"] },
      { role: "Sustainability Officer", iconKey: "sustainability", color: "#22c55e", pain: "ESG reporting is manual and retrospective. Your BMS operates at the mechanical level — you can't see room-level waste. An empty room with lights on and HVAC running but CO₂ flat? Your current systems can't even detect that.", value: "Merlin delivers 10–30% energy savings by detecting room-level waste that traditional BMS misses entirely. CO₂ and occupancy data identify empty rooms still consuming energy. Automated reports align with BREEAM, LEED, and regulatory frameworks. When you reduce consumption, you can show exactly where, when, and by how much.", benefits: ["10–30% energy savings on lighting and HVAC", "Room-level waste detection vs mechanical-level BMS", "Automated BREEAM / LEED evidence", "CO₂-flat empty rooms flagged automatically"] },
      { role: "Head of Security", iconKey: "security", color: "#f59e0b", pain: "Your access control, cameras, and alarm systems are disconnected. Patrol logs are paper-based and unverifiable. A lighting failure in a stairwell or parking garage goes unnoticed until someone reports it. Unusual activity at 2 AM in a hotel corridor? No one knows until morning.", value: "Merlin provides NFC badge-verified patrol logs with timestamped proof of presence. Lux sensors detect lighting failures in stairwells and parking areas automatically. Accelerometers detect tamper and vandalism events. Noise sensors flag unusual activity patterns — like a hotel corridor at 2 AM — and escalate in real time.", benefits: ["NFC badge-verified patrol logs", "Lux sensors detect lighting failures automatically", "Accelerometer tamper/vandalism detection", "Noise-based anomaly alerts (e.g. 2 AM corridor activity)"] },
      { role: "IT & OT Manager", iconKey: "itot", color: "#a855f7", pain: "You manage a patchwork of legacy systems, proprietary protocols, and vendor lock-in. Adding AI means adding another integration project. Security is a concern every time a new IoT device touches your network.", value: "Adaptiv devices are built with security from the silicon up. Merlin integrates with your existing SCADA, BMS, ERP, and CMMS systems via secure APIs. No protocol patchwork — one platform that talks to everything, with enterprise-grade security and on-premise deployment options.", benefits: ["Secure by design — chip to cloud", "Open API & SCADA / BMS integration", "On-premise deployment available", "Single platform, no protocol sprawl"] },
    ],
  },
  solutions: [
    { id: "building", badge: "BUILDING INTELLIGENCE", title: "The Intelligent Building That Runs Itself", challenge: "Buildings are full of systems — HVAC, lighting, security, cleaning, access control, meeting rooms — that operate in silos and respond to schedules rather than reality. 30–40% of booked meeting rooms go unused. Cleaning crews follow fixed routes whether a bathroom was visited 5 times or 500. Empty rooms run lights and HVAC while CO₂ stays flat. Facilities teams spend their days reacting to problems that should never have happened.", solution: "Merlin + Smart Displays + Sensors create a building that senses, thinks, and responds in real time. CO₂ and noise provide definitive occupancy detection without cameras. VOC levels, visit counts, and dispenser levels drive cleaning dispatch automatically. Ghost bookings are detected within minutes and rooms released. Energy waste is flagged at the room level, not the mechanical level. The result: 40–55% cleaning labor reduction, 10–30% energy savings, and 15–20% occupant satisfaction improvement.", capabilities: ["Offices: CO₂ and noise-based occupancy detection (no cameras), demand-driven HVAC and lighting, 10–30% energy savings", "Meeting rooms: Ghost booking detection within minutes, automatic room release — recovering 20% of rooms in a 200-person office = 6 added rooms, $150K–$250K saved in avoided lease expansion", "Bathrooms: VOC, visit count, and dispenser-level-driven cleaning dispatch — 40–55% labor cost reduction, near-elimination of stockout complaints", "Corridors and access: NFC badge-verified patrol logs, lux sensors detect lighting failures, accelerometer tamper detection, noise-based anomaly alerts", "Building-wide: Room-level energy waste detection (CO₂-flat room with lights on = flagged), predictive maintenance, automated BREEAM/LEED reporting"], outcomes: ["40–55% cleaning labor cost reduction", "10–30% energy savings on lighting and HVAC", "15–20% occupant satisfaction improvement", "$150K–$250K saved in avoided lease expansion", "Near-elimination of stockout complaints"], iconKey: "building", color: "#FF00B2" },
    { id: "manufacturing", badge: "MANUFACTURING", title: "Keep Your Lines Running. Automatically.", challenge: "Unplanned downtime costs manufacturers millions per hour. Manual quality inspection is slow, inconsistent, and expensive. Production data sits in silos — visible only to operators who have to act on it.", solution: "Adaptiv vibration and temperature sensors monitor critical machinery. Industrial cameras inspect production quality in real time. Smart Displays on the factory floor give operators live production KPIs and Merlin agent status. Merlin agents detect anomalies, trigger maintenance workflows, halt lines when quality deviates, and optimise scheduling automatically.", capabilities: ["Predictive maintenance — detect bearing wear, thermal anomalies, and vibration patterns before failure", "Real-time quality assurance — cameras and sensors enforce quality standards automatically", "OEE optimisation — continuous visibility into availability, performance, and quality metrics", "Production scheduling — Merlin adjusts plans based on real-time asset status", "Compliance logging — automated production records for quality certifications"], outcomes: ["Reduced unplanned downtime", "Lower maintenance costs", "Improved quality yield", "Automated compliance documentation"], iconKey: "manufacturing", color: "#14b8a6" },
    { id: "energy", badge: "ENERGY & UTILITIES", title: "Operate Your Grid Smarter. In Real Time.", challenge: "Energy infrastructure is monitored by legacy BMS systems that operate at the mechanical level — they can't see room-level waste. An empty room with lights on and HVAC running but CO₂ flat? Traditional systems can't detect that. Maintenance schedules are calendar-based, not condition-based. CO and CO₂ levels in enclosed parking garages go unmonitored until incidents occur.", solution: "Adaptiv sensors deliver 10–30% energy savings by detecting room-level waste that traditional BMS misses entirely. CO₂-flat rooms with active lighting and HVAC are flagged automatically. CO and CO₂ safety monitoring in enclosed garages prevents dangerous accumulation. Merlin agents monitor conditions, adjust loads, schedule preventive maintenance, and escalate developing issues before they cascade.", capabilities: ["Room-level waste detection — CO₂-flat room with lights on and HVAC running = waste flagged instantly, vs traditional mechanical-level BMS", "10–30% energy savings on lighting and HVAC through occupancy-driven optimization", "CO and CO₂ safety monitoring in enclosed parking garages — $5K+ avoided per emergency repair incident", "Predictive maintenance — condition-based scheduling replaces calendar-based maintenance", "Automated regulatory compliance reporting and BREEAM/LEED documentation"], outcomes: ["10–30% energy savings on lighting and HVAC", "Room-level waste detection (vs mechanical-level BMS)", "CO/CO₂ safety compliance in enclosed garages", "Automated compliance and sustainability reporting"], iconKey: "energy", color: "#6D28D9" },
    { id: "logistics", badge: "LOGISTICS & SUPPLY CHAIN", title: "Orchestrate Without Manual Intervention.", challenge: "Warehouses and logistics facilities rely on manual processes, periodic counts, and reactive exception handling. Operational visibility is retrospective. Cleaning and maintenance in large structures like parking garages follows fixed schedules regardless of actual usage. Exceptions consume disproportionate management time.", solution: "Smart Displays in warehouse zones provide real-time workflow instructions and KPIs to operators. Environmental and occupancy sensors monitor conditions, asset flows, and usage patterns. In parking structures, Merlin delivers ~1.5 FTE savings in cleaning labor per 2,000-space facility ($45K/year) and $5K+ avoided per emergency repair through predictive maintenance. Merlin automates inventory management, exception escalation, and workflow coordination across WMS and ERP systems.", capabilities: ["Inventory automation — real-time stock visibility and automatic replenishment triggers via predictive supply management", "Workflow orchestration — Merlin coordinates picking, packing, and dispatch workflows across systems", "Exception management — anomalies escalated automatically, before they compound", "Facility maintenance — demand-driven cleaning dispatch, CO/CO₂ safety monitoring in enclosed spaces, $5K+ avoided per emergency repair"], outcomes: ["Reduced manual handling errors", "~1.5 FTE cleaning savings per 2,000-space facility", "Improved inventory accuracy through predictive supply management", "CO/CO₂ safety compliance in enclosed structures"], iconKey: "logistics", color: "#FF00B2" },
    { id: "cities", badge: "SMART CITIES & INFRASTRUCTURE", title: "Protect the Infrastructure Your Communities Depend On.", challenge: "Critical infrastructure — airports, hospitals, parking structures, public spaces — is monitored intermittently or not at all. Airport cleaning teams are dispatched on fixed schedules, not correlated to actual flight arrivals. Hospital sanitization logs are paper-based and unverifiable. Parking garages lack CO/CO₂ monitoring. PRM wheelchairs go missing, wasting staff time searching.", solution: "Adaptiv sensors and Merlin agents bring intelligence to every infrastructure type. At airports: flight-correlated pre-positioning of cleaning teams achieves 50–70% reduction in SLA breaches and avoids $50K–$200K in annual contract penalties. PRM wheelchair tracking delivered 78% reduction in search time at CDG Airport. In healthcare: verified sanitization logs with environmental sensor confirmation save 80% of documentation time and $140K–$450K per prevented hospital-acquired infection. In parking: ~1.5 FTE savings per 2,000-space structure ($45K/year) with CO/CO₂ safety monitoring.", capabilities: ["Airports — flight-correlated cleaning team pre-positioning, 50–70% reduction in SLA breaches, $50K–$200K avoided in annual contract penalties", "Airports — PRM wheelchair tracking with 78% reduction in search time (proven at CDG Airport)", "Healthcare — verified sanitization logs with environmental sensor confirmation, 80% reduction in documentation time, $140K–$450K saved per prevented HAI", "Parking — ~1.5 FTE cleaning labor savings per 2,000-space structure ($45K/year), $5K+ avoided per emergency repair, CO/CO₂ safety monitoring in enclosed garages"], outcomes: ["50–70% reduction in airport SLA breaches", "78% reduction in PRM wheelchair search time", "$140K–$450K saved per prevented hospital-acquired infection", "~1.5 FTE savings per 2,000-space parking structure"], iconKey: "cities", color: "#14b8a6" },
  ],
  finalCta: {
    title: "Every environment is different. Merlin adapts.",
    body: "Tell us about your building or operation and we'll show you exactly how Merlin and Adaptiv devices work in your context.",
    cta: { label: "Talk to Our Solutions Team", href: "/contact" },
  },
};
