import type { CtaButton } from "./home";

export type SolutionsPageData = {
  metaTitle: string;
  metaDescription: string;
  hero: {
    eyebrow: string;
    titleLines: string[];
    body: string;
  };
  personasSection: {
    eyebrow: string;
    title: string;
    body: string;
    personas: {
      role: string;
      iconKey: string;
      color: string;
      pain: string;
      value: string;
      benefits: string[];
    }[];
  };
  solutions: {
    id: string;
    badge: string;
    title: string;
    challenge: string;
    solution: string;
    capabilities: string[];
    outcomes: string[];
    iconKey: string;
    color: string;
  }[];
  finalCta: {
    title: string;
    body: string;
    cta: CtaButton;
  };
};

export const solutionsDefaults: SolutionsPageData = {
  metaTitle: "Where Physical AI Goes — Solutions from Adaptiv Systems",
  metaDescription: "Buildings are the first domain. They aren't the last. Cold-chain logistics, industrial, data centers, hospitality, schools, retail, transit, smart cities — the same architecture, the same hardware, the same agent fleet.",
  hero: {
    eyebrow: "WHERE THIS TECHNOLOGY GOES",
    titleLines: ["Buildings are the first place we proved it.", "Buildings are not the limit."],
    body: "The same architecture — sensors generate telemetry, specialized agents reason over it, agents act in coordination with humans and contractors, every action is measured — generalizes to any physical-world operation. The Smart Display that lives at eye level in a corridor belongs equally on a refinery floor, beside a cold-storage door, at a hospital nurse station, in a data center aisle, or in a metro station concourse. What changes between domains isn't the device — it's which specialized agent reasons over its signals.",
  },
  personasSection: {
    eyebrow: "WHO MERLIN WORKS WITH",
    title: "The network that keeps physical spaces running.",
    body: "Merlin is built around the network of people and organizations who keep physical spaces running. The agent fleet doesn't replace them — it organizes the information flow between them and ensures every action is tracked to outcome.",
    personas: [
      { role: "Operators", iconKey: "owner", color: "#FF00B2", pain: "Facility teams, regional managers, and ownership groups responsible for the day-to-day reality of their buildings. Operating on schedules and intuition because there's no surface that turns continuous telemetry into accountable action.", value: "Merlin brings specialized AI to the operational concerns that matter most, integrated with the sensors and contractors already in place. The chat layer becomes the operator's window into the agent fleet at work.", benefits: ["Specialized agents per concern, coordinating", "Chat layer for the patterns, Smart Display for the moment", "Every action tracked, attributable, and reviewable", "Grounded in five-plus years of telemetry"] },
      { role: "Contractors & service vendors", iconKey: "facility", color: "#14b8a6", pain: "The people who actually do the work. Coordination with operators is fragmented, performance is hard to demonstrate, and the loop between recommendation and outcome is opaque.", value: "Merlin makes contractor performance visible, the coordination with operators direct, and the loop between recommendation, action, and outcome measurable.", benefits: ["Direct coordination with operators", "Performance surfaced honestly", "Outcome attribution to action", "Less time arguing, more time delivering"] },
      { role: "Technology & hardware partners", iconKey: "factory", color: "#6366f1", pain: "Makers of sensors, devices, and operational software with no platform that respects what they already build. Integration projects that take longer than the original deployment.", value: "Merlin's platform is built to extend, and the agent library is built to learn from new signals as they become available. Partners feed the fleet, the fleet pulls them forward.", benefits: ["Open to partner sensors and signals", "Agent library extends with new modalities", "Curated, not catalog-driven", "Real customers, real deployments"] },
      { role: "Investors, partners, and the curious", iconKey: "sustainability", color: "#22c55e", pain: "Watching the emergence of physical AI as a category, without a clear reference implementation to anchor on.", value: "Adaptiv has spent five years building the hardware, the deployments, and the data substrate that physical AI requires. The conversation is open.", benefits: ["Five-plus years of hardware in market", "6,000+ buildings of telemetry", "End-to-end stack ownership", "A reference implementation of the layer"] },
    ],
  },
  solutions: [
    { id: "cold-chain", badge: "COLD-CHAIN LOGISTICS", title: "Cold-chain logistics, end to end.", challenge: "Temperature-compliance intelligence has historically been trapped inside the box it monitors — one freezer, one fridge, one truck. Visibility ends at the edge of the asset. The audit trail is fragmented across systems that don't talk to each other. A regulatory event in one link of the chain doesn't surface until paperwork lands days later.", solution: "The same temperature-compliance intelligence that protects a clinical refrigerator extends across warehouses, distribution centers, transport fleets, and last-mile delivery. The Smart Display goes on the freezer door; leak detectors, door-state sensors, and dedicated temperature probes round out the mesh. End-to-end traceability for pharma, food, biologics, and reagents — with the human-facing screen exactly where staff need it.", capabilities: ["Smart Display on the freezer door — staff-facing state and one-tap acknowledgment", "Leak detectors and door-state sensors meshed through the Smart Display", "Cold-chain agent reasoning continuously, by regulatory regime", "Pharmacy temperature agent for clinical refrigeration with audit-grade traceability", "End-to-end records across pharma, food, biologics, and reagents"], outcomes: ["Continuous compliance state, visible where work happens", "Audit-grade traceability for every reading and every action", "Threshold crossings reasoned over, not just logged", "Specialized agents per regulatory regime"], iconKey: "energy", color: "#FF00B2" },
    { id: "industrial", badge: "INDUSTRIAL & MANUFACTURING", title: "Production floors with a real operator surface.", challenge: "Production-floor cleanliness, machine telemetry, safety incident response, and regulatory compliance live in different systems with different surfaces. Shift handovers are oral. Safety reporting is paper. The agent fleet has nowhere to land in the room where the work is actually happening.", solution: "Machine-vision devices catch visual anomalies in demanding environments. The Smart Display becomes the shift handover point, the safety reporting interface, and the operator's window into the agent fleet's work — all in one place on the wall. Sensors mesh through the display; agents reason continuously; operators acknowledge from the floor.", capabilities: ["Machine vision for visual anomaly detection in demanding environments", "Smart Display as shift handover and safety reporting interface", "HVAC and energy agents reasoning over the production floor", "Cleaning agent for production-floor hygiene with audit-grade events", "One physical surface for the agent fleet to land on"], outcomes: ["Operator-facing surface in the room where work happens", "Continuous reasoning across cleanliness, machines, and safety", "Audit-ready compliance evidence by default", "Shift handovers grounded in shared, current state"], iconKey: "manufacturing", color: "#14b8a6" },
    { id: "data-centers", badge: "DATA CENTERS & CRITICAL INFRASTRUCTURE", title: "Power, cooling, security at rack-level granularity.", challenge: "Data centers and critical infrastructure run on extremely precise environmental envelopes, but operational intelligence often stops at the row. Rack-level reasoning is rare. Coordination between power, cooling, security, and compliance agents is manual. A single overlooked event can cascade across systems.", solution: "Power, cooling, security, and environmental compliance at rack-level granularity. Radar occupancy sensors track who's in which aisle; leak detectors guard cooling infrastructure; Smart Displays at zone entrances surface the status of the racks behind them. Specialized agents for each concern, coordinating to keep critical systems running.", capabilities: ["Radar occupancy in aisles — privacy-safe, infrastructure-friendly", "Leak detectors meshed through Smart Displays guarding cooling infrastructure", "Smart Displays at zone entrances surfacing rack status", "Security, HVAC, and cold-chain (storage zones) agents coordinating", "Rack-level granularity, not just row-level"], outcomes: ["Rack-level intelligence on a single physical layer", "Coordinated agents for power, cooling, security, compliance", "Surface state to the operator at the entrance to the zone", "Cascading failures caught before they cascade"], iconKey: "energy", color: "#6D28D9" },
    { id: "hospitality-care", badge: "HOSPITALITY & CARE ENVIRONMENTS", title: "Hotels, senior living, and care homes.", challenge: "Hospitality and care environments share operational concerns — guest experience, housekeeping accountability, environmental compliance, resident safety — that overlap but require different specialists. A single platform that treats them as one operational mass loses the texture of each. Multiple disconnected platforms multiply integration work and create gaps between concerns.", solution: "Each operational concern gets its own specialized agent. The cleaning agent owns housekeeping accountability with audit-grade events. The HVAC agent owns environmental compliance. The security agent watches access patterns. The cold-chain agent watches medication and food storage. The Smart Display is the shared surface that staff and residents see. The chat layer is the surface management uses to ask anything across the fleet.", capabilities: ["Cleaning agent for housekeeping accountability, by SLA", "HVAC agent for environmental compliance across rooms and common areas", "Security agent for access patterns and incident response", "Pharmacy temperature agent for medication storage in care environments", "Smart Display surface for residents, staff, and guests"], outcomes: ["Specialists per concern, coordinating", "One surface for residents, one chat for management", "Audit-grade evidence for inspections by default", "Continuous compliance state without manual reporting"], iconKey: "building", color: "#a855f7" },
    { id: "schools-public", badge: "SCHOOLS, UNIVERSITIES & PUBLIC BUILDINGS", title: "Operations intelligence at the scale of an institution.", challenge: "Campus-wide operations span many spaces, many specialists, and many concerns — occupancy-driven energy, classroom utilization, environmental health, safety. No single team sees the whole picture in real time. Reporting is retrospective, fragmented, and frequently manual.", solution: "Operations intelligence at the scale of an institution. The HVAC agent reasons over campus-wide environmental health. The cleaning agent coordinates across buildings by SLA. The security agent watches access across the campus. The chat layer gives leadership a way to ask anything about anywhere — answered from the building's actual data.", capabilities: ["Occupancy-driven energy across rooms and buildings", "Classroom and shared-space utilization intelligence", "Environmental health continuously surfaced and reasoned over", "Campus-wide security agent for access patterns", "Chat layer for leadership questions across the institution"], outcomes: ["A single operational picture across many buildings", "Specialists per concern, coordinated by the fleet", "Operations intelligence at institutional scale", "Reporting that's a query, not a project"], iconKey: "building", color: "#3b82f6" },
    { id: "retail-multi", badge: "RETAIL & MULTI-SITE OPERATIONS", title: "Operational consistency across stores.", challenge: "Multi-site retail and service operations live or die by consistency — cleanliness standards, equipment reliability, customer-experience signals. Maintaining that consistency across dozens or hundreds of locations is a coordination problem. Visibility into reality at every site is the missing piece.", solution: "The agent fleet keeps the brand standard real across every location. The cleaning agent enforces SLA-driven hygiene. The HVAC agent keeps the in-store environment in band. The security agent watches access and incidents. The Smart Display is the consistent operator-facing surface in every store. The chat layer is how regional and brand leadership ask questions across the whole portfolio.", capabilities: ["Cleaning agent enforcing brand-standard hygiene", "HVAC agent keeping in-store environment in band", "Security agent watching access and incidents", "Smart Display as a consistent surface in every store", "Chat layer for regional and brand-level visibility"], outcomes: ["Brand standard kept real across every location", "Specialists per concern, consistently applied", "Real-time visibility for regional leadership", "Continuous, attributable evidence per site"], iconKey: "building", color: "#22c55e" },
    { id: "transportation", badge: "TRANSPORTATION HUBS & TRANSIT", title: "Stations, terminals, ports — at high public volume.", challenge: "Transportation hubs are high-volume public spaces with continuous operational demands across cleaning, safety, accessibility, and environmental quality. Each concern has its own contractor base, its own SLA, and its own reporting trail. Coordinating them in real time across a terminal is a structural problem.", solution: "All natural domains for specialized agents. The cleaning agent reasons over SLA-driven hygiene at high public volume. The security agent watches anomalies and access patterns. The HVAC agent keeps the environment in band despite continuous churn. The Parking agent extends to landside operations. The Smart Display gives both public and staff a shared, glanceable surface; the chat gives operations a unified view.", capabilities: ["Cleaning agent at high public volume, SLA-aware", "Security agent for anomalies and access patterns", "HVAC agent for environment in band through continuous churn", "Parking agent for landside operations", "Smart Display surface for public and staff"], outcomes: ["Specialists per concern, coordinated across the terminal", "Real-time visibility for operations leadership", "Public-facing surface that respects the audience", "A unified view across many contractor bases"], iconKey: "cities", color: "#f59e0b" },
    { id: "smart-cities", badge: "SMART CITIES & PUBLIC INFRASTRUCTURE", title: "Physical AI at municipal scale.", challenge: "Beyond single buildings, the operational fabric of districts and cities — streetlights, public restrooms, transit stops, parks, civic buildings — runs on independent contracts, fragmented data, and reporting cycles measured in weeks. Citizens experience that fragmentation directly. So does the municipality.", solution: "Physical AI at municipal scale. The same Smart Display, sensor library, and agent fleet that operate inside buildings extend to the operational fabric of districts and cities. Streetlights with embedded sensing, public restrooms with cleaning and dispenser monitoring, transit stops with environmental and security agents, civic buildings with the full stack — all reasoning on one platform.", capabilities: ["Streetlight illumination + occupancy + energy sensing", "Public restrooms with cleaning, dispenser, and occupancy intelligence", "Transit stops with environmental and security agents", "Civic buildings with the full stack — same agents, same surface", "One platform across the operational fabric of a city"], outcomes: ["Specialists per concern, deployed at city scale", "Operational fabric reasoned over continuously", "Public-facing surface where citizens use the space", "Reporting that matches the pace of operations, not the pace of bureaucracy"], iconKey: "cities", color: "#14b8a6" },
  ],
  finalCta: {
    title: "Sensors generate signal. Specialized agents reason. Humans and vendors execute.",
    body: "Whether the physical environment is a warehouse, a hospital, a refinery, or a metro station — the architecture works because the loop is the same, and the hardware that runs the loop is the same too. One platform, many environments, one foundation underneath.",
    cta: { label: "Talk to us", href: "/contact" },
  },
};
